version: "3.8"

services:
  app:
    build: .  # O "." indica que a imagem será construída no diretório atual
    command: /bin/sh -c "npm install && npm start"  # Comando para rodar o app
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do contêiner para a 5000 na máquina
    volumes:
      - .:/usr/app  # Mapeia o diretório atual da máquina para /usr/app no contêiner
      - ./.env:/usr/app/.env  # Mapeia o .env para o contêiner
    depends_on:
      - db  # O serviço app depende do banco de dados db

  db:
    image: mysql:8.0  # Usando a imagem oficial do MySQL
    restart: always  # Configuração para reiniciar o contêiner automaticamente
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vio_leonardo
    ports:
      - "3306:3306"  # Porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql  # Volume para persistência de dados do MySQL
      - ./mysql-init:/docker-entrypoint-initdb.d  # Scripts de inicialização do banco de dados

volumes:
  db_data:  # Volume persistente para dados do MySQL
